services:
    axum-oauth-docker:
        container_name: axum-oauth-docker
        build:
            context: .
        ports:
            - "127.0.0.1:3011:3011"
        restart: always
        volumes:
            - type: bind
              source: ./.env
              target: /opt/.env
              read_only: true
            - type: bind
              source: ./db
              target: /opt/db
              read_only: false
